spring.application.name=ecomm_backend

#db config
spring.datasource.url=jdbc:postgresql://localhost:5432/e_commerce_application
spring.datasource.username=postgres
spring.datasource.password=1264
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Keeps the schema in sync with your entities
spring.jpa.hibernate.ddl-auto=update
#create, update, create-drop, validate

spring.jpa.show-sql=true

#format time in time to local time zone : NOT RECOMMENDED
spring.jackson.date-format=dd-MM-yyyy HH:mm:ss
spring.jackson.time-zone=Asia/Kolkata